# Generated by Django 3.2.5 on 2021-07-24 14:30

import cloudinary.models
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0003_auto_20210724_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_picture',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2021, 7, 24, 14, 28, 36, 546193, tzinfo=utc), max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2021, 7, 24, 14, 30, 0, 789356, tzinfo=utc), max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
