# Generated by Django 3.2.5 on 2021-07-25 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myhood', '0003_alter_neighbourhood_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='idNo',
            new_name='id_number',
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
