# Generated by Django 3.2.5 on 2021-07-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0005_auto_20210725_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
