# Generated by Django 3.2.5 on 2021-07-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0006_business_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
